version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3001:80"
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
  
  redis:
    image: redis
